context("Create GT variables")
context("Drop rows missing gt variables")
context("Subset to observed geo periods")
context("Count respondent trials")
context("Summarize design effects")
context("Count level2 groups")
context("Create ZZ")
context("Make NNl2")
context("Make dummy weight matrix")
context("Make group grid")
context("Make group identifier")
context("Make l2_only")
context("Make missingness array")
context("Make ns_long")
context("Make ns_long_obs")
context("Summarize mean_y")
context("Summarize success count")
context("Summarize trial counts")
context("Summarize trials by period")
