// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// is_greater
Rcpp::IntegerVector is_greater(Rcpp::NumericVector response, int level);
RcppExport SEXP dgirt_is_greater(SEXP responseSEXP, SEXP levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type response(responseSEXP);
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    __result = Rcpp::wrap(is_greater(response, level));
    return __result;
END_RCPP
}
