// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// is_greater
DataFrame is_greater(NumericVector response, IntegerVector levels);
RcppExport SEXP dgirt_is_greater(SEXP responseSEXP, SEXP levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type response(responseSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type levels(levelsSEXP);
    __result = Rcpp::wrap(is_greater(response, levels));
    return __result;
END_RCPP
}
