// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// make_gt
arma::vec make_gt(arma::vec values, int gt);
RcppExport SEXP dgirt_make_gt(SEXP valuesSEXP, SEXP gtSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< int >::type gt(gtSEXP);
    __result = Rcpp::wrap(make_gt(values, gt));
    return __result;
END_RCPP
}
