setClass("Control",
         slots = list(constant_item = "logical",
                      geo_name = "character",
                      geo_filter = "character",
                      group_names = "character",
                      item_names = "character",
                      aggregate_item_names = "character",
                      min_survey_filter = "numeric",
                      min_t_filter = "numeric",
                      modifier_names = "character",
                      prop_name = "character",
                      strata_names = "character",
                      survey_name = "character",
                      target_group_names = "character",
                      target_proportion_name = "character",
                      t1_modifier_names = "character",
                      time_name = "character",
                      time_filter = "numeric",
                      weight_name = "character"),
         prototype = prototype(constant_item = TRUE,
                               min_t_filter = 1L,
                               min_survey_filter = 1L,
                               prop_name = "proportion"))
