# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
dichotomize_cpp <- function(response) {
    .Call('dgirt_dichotomize_cpp', PACKAGE = 'dgirt', response)
}

